### ISSUE TITLE
"Legendary" card keyword/field to prevent duplication/transform/remove

### ISSUE THREAD

**Issue by dbjorge** [dbjorge/jorbs-spire-mod#131]
*note: this is going to be a fairly complicated effect; if you're looking for a good first issue to tackle, this probably isn't it*

Per discord discussion, we want to add this for `ForbiddenGrimoire` and for several of the proposed Explorer cards later. Should act similarly to Ascender's Bane:

> Legendary cards cannot be duplicated, transformed, or removed from your deck.

Should still allow exhaust (different from necronomicurse)

Specific interactions should include (but probably won't be limited to):
* Patch `Astrolabe::onEquip` to ignore them
* Patch `CardGroup::getPurgeableCards` to omit them (but ideally also patch earlier rewards/etc to avoid choosing them as input)
* Patch `CardLibrary::getCurse` to omit them (if necessary? not sure if they exist to start)
* Add `AbstractCard.onRemoveFromMasterDeck` effect similar to `Necronomicurse`'s
* Patch `DollysMirror.onEquip` to omit it (this will probably need an `Instrument` patch)
* Patch `AbstractDungeon.transformCard` to omit them (but ideally also patch earlier rewards/etc to avoid choosing them as input) - hopefully the `getPurgableCards` patch covers this for most cases, eg it does for `NeowReward`'s transform option
    * Note, they shouldn't be candidates to be transformed to OR from
* string search through base game jar for other cases that special case IDs "AscendersBane" or "Necronomicurse"

Specific interactions to test include (not an exhaustive list):
* Card remove: `NewoReward`, bird cage, shop remove, the curse remove event, the pay health to remove, beggar, toke
* Transform: astrolabe, `NeowReward`, events
* Duplicate: `DollysMirror`

**Comment by dbjorge** [comment]
This is a general enough effect that we should look around to see if any other mods have already worked out how to implement something similar; search on GitHub, search and ask in the Slay the Spire discord' #modding channel

**Comment by Frenoss** [comment]
Can a legendary card be added in battle by an effect that generates a new card? (Yes, because it seems more fun. "No" would be easier to implement, at least.)
Should a generated legendary card persist to the master deck? (No, because that's the expectation for cards added during battle. "Yes" seems a little more in theme with the indestructible nature of legendary things, though.)

**Comment by dbjorge** [comment]
No, they should be exempt from skill potions/etc.

**Comment by Frenoss** [comment]
Would it be right to say that a legendary card only enters your deck in these ways?
* a starting card
* a card reward after a battle
* specifically (by name or by category of Legendary) given by some artifact

**Comment by wang429** [comment]
Heads up, main branch Calling Bell can give the Grimoire.

**Comment by dbjorge** [comment]
My understanding is that not even the second one should be available (ie, they should be CardRarity.SPECIAL and not appear in any pools)

**Comment by Frenoss** [comment]
Oh, the problem is just preventing them from leaving the deck. I had thought entering was also something to solve, but `CardRarity.SPECIAL` should fix all or most of that.

My apologies, I don't understand how Calling Bell gives the Grimoire. Do you mean indirectly, by giving a relic that then gives the Grimoire? Or how does it do it?

**Comment by wang429** [comment]
It was mentioned in the Discord https://cdn.discordapp.com/attachments/624999371594793000/643966968658919427/unknown.png
Not really sure exactly why it happened atm

**Comment by wang429** [comment]
Unless I'm reading it wrong, `AbstractDungeon.initializeCardPools()` both adds to the curseCardPool by Rarity and by card type - `AbstractDungeon.addCurseCards()`

**Comment by Frenoss** [comment]
Haha, thanks. You're first mistake was thinking I'm not dumb. TIL Forbidden Grimoire is a curse card! I'll probably add a PostDungeonInitialize listener and remove it from the pool.

**Comment by wang429** [comment]
It's interestingly strange that curseCardPool is added to twice on initialize.

**Comment by Frenoss** [comment]
If I see what you're looking at, the first time initializes the pool with all curses. The second then adds to it with anything that's a curse in the set of reward cards. It is strange.

**Comment by wang429** [comment]
Yeah, that sounds like what I was seeing.

**Comment by Frenoss** [comment]
I have a set of changes that accomplishes 80%. What's missing is validation that *transformCard is never called on a Legendary, raw patches for DollysMirror and FountainOfCurseRemoval, and onRemoveFromMasterDeck. Basically, most known situations work, and we're missing logging or extra care for when something unanticipated happens (say, our mod in conjunction with another).

I'll submit a PR for what's there, and you can push it back if you want to wait for everything. My schedule will let me finish it in the next two days.

**Comment by dbjorge** [comment]
Issue not quite resolved yet; 44d09ee is the 80% there patch, leaving issue open for the remaining 20%

**Comment by dbjorge** [comment]
Implemented the Fountain of Curse Removal and Dolly's Mirror patches

**Comment by Frenoss** [comment]
Thanks for those patches! I was leery about learning the syntax. Seeing them makes it seem easy enough, which is good, because AbstractPlayer.isCursed needs one. Or just effectively replace with a Postfix patch. While an Instrument patch seems less stable, it also seems more respectful of other mods changes, versus me just rewriting what the routine does in a Postfix patch. And, since we have Instrument patches now anyway, I expect to lean that direction.

Summary of known work remaining:
* patch `AbstractPlayer.isCursed`
* validate card in `AbstractDungeon.transformCard` and `srcTransformCard`
* do something, maybe just log, maybe prevent removal, in `CardGroup.removeCard` related to `onRemoveFromMasterDeck`
