### ISSUE TITLE
Improve Misty Step display of BaseBlock number

### ISSUE THREAD

**Issue by Frenoss** [dbjorge/jorbs-spire-mod#133]
Does BaseBlock have a future purpose different from magic numbers, such as rendering in a different color? Misty Step doesn't show its base block number as upgraded, in terms of color. It seems simpler, in terms of overall concepts in the mod, to use a magic number. Misty Step could also just mark the base block as upgraded to get the highlight effect.

**Comment by Frenoss** [comment]
Labeled as in, once the question is answered, it's a good first issue either way.

**Comment by dbjorge** [comment]
If I recall correctly, I did it this way for consistency with similar "per clarity" damage effects, where using baseDamage instead of a magic number is important for the purposes of including Wrath in the display. I don't think it would cause any problems to use an `urMagicNumber` for Misty Step, but since we're going to want to solve the same problem for the `BaseDamageNumber` cases anyway, probably it would be reasonable to solve it the same way for `BaseBlockNumber`

**Comment by Frenoss** [comment]
Now that I see what it's intended to do, I'm going to think whether this change has enough merit. I think it might be large work for not revelatory information.

**Comment by dbjorge** [comment]
Don't think this is worth the work
