### ISSUE TITLE
Cards that Snap will leave a stack of coil after snap

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#172]
Trauma at the time of writing
Found while implementing Purge Mind

**Comment by dbjorge** [comment]
Good catch, I think this is a regression from when the static memory arc was introduced. Probably the right fix will be to move the `MemoryManager::snap` call in SnapAction into a separate sub-action that gets queued immediately after `SnappedPower` is applied.

**Comment by dbjorge** [comment]
Actually, now that there's a secondary interaction with Coil that motivates keeping it around post-snap (Snake Oil), I think it's by design that this happens; you remembered patience at the time you played the card, so I think the most reasonable reading is for you to still gain the coil stack even if snapping also happens when you play the card.
