### ISSUE TITLE
Strange behavior in compendium view with Wanderer rares

### ISSUE THREAD

**Issue by Frenoss** [dbjorge/jorbs-spire-mod#19]
Viewing cards in the compendium works as expected looking through the common and uncommon cards. With the "View Upgrade" option checked, a freeze-draw-resetToUnupgraded loop happens in the area of the rare cards.

**Comment by Frenoss** [comment]
Maybe just a symptom of what's catching the timeout, but debug message happens every second when the issue is being experienced:
cards.AbstractCard> Card Image load time: 981ms

**Comment by Frenoss** [comment]
Hibernate, Rest, and Thorns are very similar Skill cards that show the different behaviors. Hibernate always works. Thorns always fails. Rest fails if the previous card failed and works if the previous card worked. Inspection of just their code and strings doesn't reveal anything to me.

**Comment by dbjorge** [comment]
Wow, gross bug. The issue is actually not with any of the cards you've mentioned; it's actually a bug in the `upgrade()` method of the card `Banish`, where it called `initialize()` instead of `initializeDescription()` like it's supposed to. Apparently the "upgrade" method for **every card currently *visible* in the library behind the selected card** is part of the update loop once you select the "view upgrade" option, and `initialize()` is a static `AbstractCard` method that synchronously reloads several texture files, which takes longer than a render/update tick to do, which effectively cuts off a bunch of input processing that "finishes" the act of selecting the view upgrades option.

**Comment by Frenoss** [comment]
Nice debugging. What a find. :)
