### ISSUE TITLE
Guardian stuck in Shell animation - no Defensive Stance rotation

### ISSUE THREAD

**Issue by robfuscatory** [dbjorge/jorbs-spire-mod#535]
**Version**
BETA - 2.1

**Describe the bug**
Color spray's "stasis"(?) debuff (the one that forces no action until the next turn) caused Guardian to skip his Defensive stance rotation even after receiving 35 damage.

**To Reproduce**
1. Play Color Spray, giving Guardian the debuff where no action takes place until next turn - sorry, random!  see screenshot for seed
2. Triggered Guardian Stance change
3. No action took place this turn
4. Next turn he did his large attack but appearing in this stance.  He did not receive his thorns buff
5. I took this screenshot on the following turn as he was about to Steam Vent me from his defensive stance.  He lost his "X more damage until stance change" buff now as well.

**Expected behavior**
I would've expected him to skip one turn, but then enter his defensive stance attack rotation.  I'm curious if this is intended, that it literally skips the action of him moving into that stance (but to my detriment, as I was unable to avoid his large attack this way).  

**Screenshot**
![guardian_permashell](https://user-images.githubusercontent.com/2294163/95910249-c43f2100-0d6d-11eb-8a3f-eef5b2dd7f48.png)

2nd screenshot - he never went back into normal rotation; just kept cycling through steam vent / block / big attack cycle, since he lost his "X Damage until stance change" buff.  This seems unintentional
![guardian_permashell_2](https://user-images.githubusercontent.com/2294163/95910630-58a98380-0d6e-11eb-83a9-85218f38c006.png)

**Comment by wang429** [comment]
Thanks for the report!

Is exploiting this bug the way Wanderer can reliably beat the Guardian? 😂

**Comment by wang429** [comment]
I haven't been able to reproduce this on the latest builds of Slay the Spire Main (12-22-2020) and the latest builds of JorbsMod (1.9.2). It's possible the bug was fixed indirectly or a dependency resolved it, but I can't find any specific change between the time of reporting and now that would have touched this if the bug was actually fixed. There were some bug fixes up through JorbsMod versions 1.6 that addressed some issues with Banish which could have benefited the situation here, but those were at latest from February 2020.

Closing this ticket because unable to reproduce, but please reopen or file a new ticket if this is encountered again.
